### ISSUE TITLE
我也最近在用Cython封装CTP可以发布源码一起学习么

### ISSUE THREAD

**Issue by 345161974** [xushenkun/cyctp#1]
Hi，我在Pypi上看到你有上传模块。但是根据信息查找到你的github，并没有看到源码。方便公布源码么？我也是最近在学习Cython封装CTP的。希望可以一起交流学习。

**Comment by xushenkun** [comment]
不好意思，刚看见，一起学习。

**Comment by 345161974** [comment]
@xushenkun 多谢!
